package com.pulse.entity;

public enum AuditLogEventType {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    GROUP_CREATED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    GROUP_LEFT,
    GROUP_INVITE_CREATED,
    GROUP_INVITE_ACCEPTED,
    GROUP_INVITE_DECLINED
}